# Generated by Django 2.0.2 on 2018-02-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0002_reddit_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='reddit_post',
            name='subreddit',
            field=models.CharField(default='', max_length=200),
        ),
    ]
