# Generated by Django 2.0.2 on 2018-02-12 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0003_reddit_post_subreddit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reddit_post',
            unique_together={('subreddit', 'title', 'pub_date')},
        ),
    ]
