# Generated by Django 2.0.2 on 2018-03-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0004_auto_20180211_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='reddit_post',
            name='link',
            field=models.CharField(default='', max_length=250),
        ),
    ]
