# Generated by Django 2.0.3 on 2018-03-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0005_reddit_post_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saved_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=-1)),
                ('post_type', models.CharField(default='null', max_length=20)),
                ('postid', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Twitter_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=350)),
                ('username', models.CharField(default='', max_length=100)),
                ('handle', models.CharField(default='', max_length=100)),
                ('pub_date', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='twitter_post',
            unique_together={('message', 'handle', 'username', 'pub_date')},
        ),
    ]
