# Generated by Django 2.0.3 on 2018-03-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0006_auto_20180315_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=-2)),
                ('username', models.CharField(default='null', max_length=100)),
            ],
        ),
    ]
