# Generated by Django 2.0.3 on 2018-03-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0008_twitter_post_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitter_post',
            name='urls',
            field=models.CharField(default='', max_length=300),
        ),
    ]
