# Generated by Django 2.0.3 on 2018-03-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0009_twitter_post_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitter_post',
            name='urls',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
