# Generated by Django 2.0.3 on 2018-03-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0010_auto_20180315_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitter_post',
            name='urls',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
