# Generated by Django 2.0.2 on 2018-03-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0013_twitter_post_mentions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ytid', models.CharField(default='', max_length=20)),
                ('searchQuery', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='youtube_post',
            unique_together={('ytid', 'searchQuery')},
        ),
    ]
