# Generated by Django 2.0.2 on 2018-03-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0014_auto_20180316_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitter_post',
            name='searchQuery',
            field=models.CharField(default='', max_length=200),
        ),
    ]
